<?php

/**
 * This is the model base class for the table "disease_medicine".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DiseaseMedicine".
 *
 * Columns in table "disease_medicine" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idmedicine
 * @property integer $iddisease
 *
 */
abstract class BaseDiseaseMedicine extends GxActiveRecord {
    
    
        
    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'disease_medicine';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'DiseaseMedicine|DiseaseMedicines', $n);
    }

    public static function representingColumn() {
        return array(
            'idmedicine',
            'iddisease',
        );
    }

    public function rules() {
        return array(
            array('idmedicine, iddisease', 'required'),
            array('idmedicine, iddisease', 'numerical', 'integerOnly'=>true),
            array('idmedicine, iddisease', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'idmedicine' => null,
            'iddisease' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('idmedicine', $this->idmedicine);
        $criteria->compare('iddisease', $this->iddisease);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}