<?php

/**
 * This is the model base class for the table "consults".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Consults".
 *
 * Columns in table "consults" available as properties of the model,
 * followed by relations of table "consults" available as properties of the model.
 *
 * @property integer $idconsults
 * @property string $date_consultation
 * @property string $local
 * @property string $note
 * @property string $notify
 * @property string $image
 * @property string $file
 * @property integer $iddoctor
 * @property string $date
 * @property integer $iduser
 *
 * @property Doctor $doctor
 * @property User $user
 */
abstract class BaseConsults extends GxActiveRecord {
	
    
    public $image_delete;
	public $file_delete;
	    
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'consults';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Consults|Consults', $n);
	}

	public static function representingColumn() {
		return array('date_consultation');
	}

	public function rules() {
		return array(
			array('iduser', 'required'),
			array('iddoctor, iduser', 'numerical', 'integerOnly'=>true),
			array('local', 'length', 'max'=>200),
			array('notify', 'length', 'max'=>1),
			array('image', 'length', 'max'=>120),
			array('file', 'length', 'max'=>130),
			array('note, date', 'safe'),
			array('image', 'file', 'types'=>'jpg,png', 'allowEmpty'=>true),
			array('image_delete', 'length', 'max'=>1),
			// array('file', 'allowEmpty'=>true),
			// array('file_delete', 'length', 'max'=>1),
			array('local, note, notify, image, file, iddoctor, date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idconsults, date_consultation, local, note, notify, image, file, iddoctor, date, iduser', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'doctor' => array(self::BELONGS_TO, 'Doctor', 'iddoctor'),
			'user' => array(self::BELONGS_TO, 'User', 'iduser'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idconsults' => Yii::t('app', 'Idconsults'),
			'date_consultation' => Yii::t('app', 'Date Consultation'),
			'local' => Yii::t('app', 'Local'),
			'note' => Yii::t('app', 'Note'),
			'notify' => Yii::t('app', 'Notify'),
			'image' => Yii::t('app', 'Image'),
			'file' => Yii::t('app', 'File'),
			'iddoctor' => null,
			'date' => Yii::t('app', 'Date'),
			'iduser' => null,
			'doctor' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idconsults', $this->idconsults);
		$criteria->compare('date_consultation', $this->date_consultation, true);
		$criteria->compare('local', $this->local, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('notify', $this->notify, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('file', $this->file, true);
		$criteria->compare('iddoctor', $this->iddoctor);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('iduser', $this->iduser);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}